package org.polytech.agent;

public enum TypeOffer {
    INITIAL,
    FIRST_ACCEPT,
    END_NEGOCIATION,
    DEMAND_CONFIRMATION_ACHAT,
    POSITIVE_RESPONSE_CONFIRMATION_ACHAT,
    NEGATIVE_RESPONSE_CONFIRMATION_ACHAT,
    AGAINST_PROPOSITION;
}
